baseURL = "https://remywang22.github.io/"
languageCode = "zh-cn"
title = "Remy's Blog"
theme = "PaperMod"

[params]
    author = "Remy"
    defaultTheme = "auto"
relativeURLs = true
canonifyURLs = true